# Generated by Django 5.2.5 on 2025-08-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='ebooks/')),
                ('cover_image', models.ImageField(blank=True, upload_to='covers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
